services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: smart_energy_agent_dev
    restart: unless-stopped
    privileged: true
    network_mode: host

    volumes:
      - ./config.json:/app/config.json:rw
      - ./gpio_mapping.json:/app/gpio_mapping.json:rw
      - ./logs:/app/logs:rw

    environment:
      LOG_DIR: /app/logs

    env_file:
      - .env
